# Generated by Django 5.0.3 on 2025-12-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_message_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='randomtest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
