# Generated by Django 5.0.3 on 2025-12-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_randomtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('kvk', models.CharField(max_length=15)),
            ],
        ),
    ]
